name: Update weekly tips
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with my latest weekly tips
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "http://incrementalelm.com/tips/feed.xml"
          max_post_count: 3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "ELM-RADIO-LIST"
          feed_list: "https://elm-radio.com/feed.xml"
          max_post_count: 3
